"""SkillTrainer — daily backtest loop that generates improved skill prompt versions.

Registered as a Celery periodic task (runs at 3am UTC daily).

CRITICAL RULE: NEVER auto-promote skill versions. Human approval is ALWAYS required.
The trainer creates canary versions and flags them for review. Humans decide.
"""

from __future__ import annotations

import logging
from datetime import UTC, datetime, timedelta

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.models.skill import Skill
from app.db.models.workflow import RunStep
from app.db.session import get_db_context
from app.repositories import skill_version as skill_version_repo
from app.services.skill_version import SkillVersionService

logger = logging.getLogger(__name__)

_WINRATE_IMPROVEMENT_THRESHOLD = 0.80  # Below this → attempt to improve
_META_PROMPT_TEMPLATE = """\
You are an AI prompt engineer improving an agent skill fragment.

Skill name: {skill_name}
Skill category: {skill_category}

Current prompt fragment (appended to agent system prompt):
---
{current_fragment}
---

Recent failure patterns from the last 24h runs using this skill:
{failure_summaries}

Total runs: {total_runs}
Successful runs: {successful_runs}
Winrate: {winrate:.0%}

Write an improved prompt fragment that addresses the failure patterns above.
Keep it concise (under 500 words). Output ONLY the improved fragment, no explanation."""


class SkillTrainer:
    def __init__(self, db: AsyncSession) -> None:
        self.db = db

    async def run_daily_loop(self) -> dict:
        """Evaluate all active skills used in the last 24h and generate improved versions.

        Returns a summary dict: skills_evaluated, versions_created, skipped.
        NEVER calls approve(). Human approval required always.
        """
        since = datetime.now(UTC) - timedelta(hours=24)
        skills = await self._get_active_skills()
        skills_evaluated = 0
        versions_created = 0
        skipped = 0

        for skill in skills:
            try:
                result = await self._evaluate_skill(skill, since)
                skills_evaluated += 1
                if result == "created":
                    versions_created += 1
                else:
                    skipped += 1
            except Exception as exc:
                logger.warning("SkillTrainer: error evaluating skill %s: %s", skill.id, exc)
                skipped += 1

        summary = {
            "skills_evaluated": skills_evaluated,
            "versions_created": versions_created,
            "skipped": skipped,
            "run_at": datetime.now(UTC).isoformat(),
        }
        logger.info("SkillTrainer daily loop complete: %s", summary)
        return summary

    async def _evaluate_skill(self, skill: Skill, since: datetime) -> str:
        """Evaluate one skill and optionally create a canary version. Returns 'created'|'skipped'."""
        total, successful, failure_summaries = await self._gather_run_outcomes(skill, since)

        if total < 5:
            return "skipped"  # Not enough data

        winrate = successful / total if total > 0 else 1.0

        if winrate >= _WINRATE_IMPROVEMENT_THRESHOLD:
            return "skipped"  # Already performing well

        # Check if a canary already exists for this skill
        existing_canary = await skill_version_repo.get_canary(self.db, skill.id)
        if existing_canary:
            return "skipped"  # Already have a pending canary

        improved_fragment = await self._generate_improved_fragment(
            skill=skill,
            total_runs=total,
            successful_runs=successful,
            winrate=winrate,
            failure_summaries=failure_summaries,
        )
        if not improved_fragment:
            return "skipped"

        svc = SkillVersionService(self.db)
        await svc.create_version(
            skill_id=skill.id,
            prompt_fragment=improved_fragment,
            notes=f"Auto-generated by SkillTrainer on {datetime.now(UTC).date()} "
            f"(winrate {winrate:.0%}, {total} runs evaluated)",
        )
        return "created"

    async def _gather_run_outcomes(
        self, skill: Skill, since: datetime
    ) -> tuple[int, int, list[str]]:
        """Count run steps that used this skill in the last 24h. Returns (total, successful, failure_summaries)."""
        result = await self.db.execute(
            select(RunStep)
            .where(
                RunStep.created_at >= since,
                RunStep.status.in_(["completed", "failed"]),
            )
            .limit(200)
        )
        steps = result.scalars().all()

        skill_id_str = str(skill.id)
        relevant = [
            s
            for s in steps
            if skill_id_str in str(s.output_json or {})
            or skill_id_str in str(getattr(s, "step_config", {}) or {})
        ]

        total = len(relevant)
        successful = sum(1 for s in relevant if s.status == "completed")
        failure_summaries: list[str] = []
        for s in relevant:
            if s.status == "failed":
                err = (s.output_json or {}).get("error", "unknown error")
                failure_summaries.append(str(err)[:200])

        return total, successful, failure_summaries[:10]

    async def _generate_improved_fragment(
        self,
        *,
        skill: Skill,
        total_runs: int,
        successful_runs: int,
        winrate: float,
        failure_summaries: list[str],
    ) -> str | None:
        """Call Anthropic API to generate an improved prompt fragment."""
        try:
            from app.services.runtime.anthropic_api import run_agent as anthropic_run
        except ImportError:
            logger.warning("SkillTrainer: anthropic_api not available")
            return None

        failures_text = (
            "\n".join(f"- {f}" for f in failure_summaries) or "- No specific failures captured"
        )
        meta_prompt = _META_PROMPT_TEMPLATE.format(
            skill_name=skill.name,
            skill_category=skill.category,
            current_fragment=skill.system_prompt_fragment,
            failure_summaries=failures_text,
            total_runs=total_runs,
            successful_runs=successful_runs,
            winrate=winrate,
        )

        try:
            # Use a simple mock AgentConfig-like object for the API call
            class _MockAgent:
                runtime_kind = "anthropic-api"
                model = "claude-haiku-4-5-20251001"
                max_tokens = 1024
                temperature = 40  # 0.4 x100

            output, _ = await anthropic_run(
                prompt=meta_prompt,
                system_prompt="You are a prompt engineering assistant. Output only the requested content.",
                model="claude-haiku-4-5-20251001",
                max_tokens=1024,
                temperature=0.4,
            )
            return output.strip() if output else None
        except Exception as exc:
            logger.warning("SkillTrainer: LLM call failed for skill %s: %s", skill.id, exc)
            return None

    async def _get_active_skills(self) -> list[Skill]:
        result = await self.db.execute(select(Skill).where(Skill.is_active.is_(True)).limit(100))
        return list(result.scalars().all())


async def run_skill_trainer() -> None:
    """Celery task entry point — called by the beat schedule."""
    async with get_db_context() as db:
        trainer = SkillTrainer(db)
        await trainer.run_daily_loop()
