"""add_agent_templates

Revision ID: 9d4e2f1a8c3b
Revises: 8c275862b6d5
Create Date: 2026-06-03 14:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d4e2f1a8c3b'
down_revision: Union[str, None] = '8c275862b6d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_key', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('default_tools_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('default_tool_permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('default_runtime_kind', sa.String(length=32), nullable=False),
    sa.Column('default_model', sa.String(length=120), nullable=False),
    sa.Column('default_avatar', sa.String(length=120), nullable=False),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('popularity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_templates_pkey'))
    )
    op.create_index(op.f('agent_templates_category_idx'), 'agent_templates', ['category'], unique=False)
    op.create_index(op.f('agent_templates_is_active_idx'), 'agent_templates', ['is_active'], unique=False)
    op.create_index(op.f('agent_templates_source_idx'), 'agent_templates', ['source'], unique=False)
    op.create_index(op.f('agent_templates_source_key_idx'), 'agent_templates', ['source_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('agent_templates_source_key_idx'), table_name='agent_templates')
    op.drop_index(op.f('agent_templates_source_idx'), table_name='agent_templates')
    op.drop_index(op.f('agent_templates_is_active_idx'), table_name='agent_templates')
    op.drop_index(op.f('agent_templates_category_idx'), table_name='agent_templates')
    op.drop_table('agent_templates')
    # ### end Alembic commands ###
