"""add_handoffs_secrets_integrations

Revision ID: 8c275862b6d5
Revises: 0023_skills_recovery
Create Date: 2026-06-03 12:19:54.747294

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c275862b6d5"
down_revision: str | None = "0023_skills_recovery"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "integrations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("config_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("last_check_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("integrations_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("integrations_pkey")),
    )
    op.create_index(op.f("integrations_user_id_idx"), "integrations", ["user_id"], unique=False)
    op.create_table(
        "secrets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("environment", sa.String(length=32), nullable=False),
        sa.Column("value_encrypted", sa.Text(), nullable=False),
        sa.Column("value_masked", sa.String(length=255), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("secrets_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("secrets_pkey")),
    )
    op.create_index(op.f("secrets_user_id_idx"), "secrets", ["user_id"], unique=False)
    op.create_table(
        "handoffs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("from_step_id", sa.UUID(), nullable=True),
        sa.Column("to_step_id", sa.UUID(), nullable=True),
        sa.Column("from_agent_id", sa.UUID(), nullable=True),
        sa.Column("to_agent_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("package_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("quality_gate_result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_reason", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
            name=op.f("handoffs_approved_by_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["from_agent_id"],
            ["agent_configs.id"],
            name=op.f("handoffs_from_agent_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["from_step_id"],
            ["run_steps.id"],
            name=op.f("handoffs_from_step_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("handoffs_project_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("handoffs_run_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["to_agent_id"],
            ["agent_configs.id"],
            name=op.f("handoffs_to_agent_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["to_step_id"],
            ["run_steps.id"],
            name=op.f("handoffs_to_step_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("handoffs_pkey")),
    )
    op.create_index(op.f("handoffs_from_agent_id_idx"), "handoffs", ["from_agent_id"], unique=False)
    op.create_index(op.f("handoffs_from_step_id_idx"), "handoffs", ["from_step_id"], unique=False)
    op.create_index(op.f("handoffs_project_id_idx"), "handoffs", ["project_id"], unique=False)
    op.create_index(op.f("handoffs_run_id_idx"), "handoffs", ["run_id"], unique=False)
    op.create_index(op.f("handoffs_to_agent_id_idx"), "handoffs", ["to_agent_id"], unique=False)
    op.create_index(op.f("handoffs_to_step_id_idx"), "handoffs", ["to_step_id"], unique=False)
    op.drop_index(op.f("ix_agent_configs_project_id"), table_name="agent_configs")
    op.create_index(
        op.f("agent_configs_project_id_idx"), "agent_configs", ["project_id"], unique=False
    )
    op.drop_index(op.f("ix_chat_files_user_id"), table_name="chat_files")
    op.create_index(op.f("chat_files_user_id_idx"), "chat_files", ["user_id"], unique=False)
    op.drop_index(op.f("ix_conversation_shares_conversation_id"), table_name="conversation_shares")
    op.drop_index(op.f("ix_conversation_shares_shared_with"), table_name="conversation_shares")
    op.create_index(
        op.f("conversation_shares_conversation_id_idx"),
        "conversation_shares",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("conversation_shares_shared_with_idx"),
        "conversation_shares",
        ["shared_with"],
        unique=False,
    )
    op.drop_index(op.f("ix_conversations_user_id"), table_name="conversations")
    op.create_index(op.f("conversations_user_id_idx"), "conversations", ["user_id"], unique=False)
    op.drop_index(op.f("ix_knowledge_documents_agent_config_id"), table_name="knowledge_documents")
    op.drop_index(op.f("ix_knowledge_documents_project_id"), table_name="knowledge_documents")
    op.create_index(
        op.f("knowledge_documents_agent_config_id_idx"),
        "knowledge_documents",
        ["agent_config_id"],
        unique=False,
    )
    op.create_index(
        op.f("knowledge_documents_project_id_idx"),
        "knowledge_documents",
        ["project_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_message_ratings_message_id"), table_name="message_ratings")
    op.drop_index(op.f("ix_message_ratings_user_id"), table_name="message_ratings")
    op.create_index(
        op.f("message_ratings_message_id_idx"), "message_ratings", ["message_id"], unique=False
    )
    op.create_index(
        op.f("message_ratings_user_id_idx"), "message_ratings", ["user_id"], unique=False
    )
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.create_index(
        op.f("messages_conversation_id_idx"), "messages", ["conversation_id"], unique=False
    )
    op.drop_index(op.f("ix_projects_slug"), table_name="projects")
    op.drop_index(op.f("ix_projects_user_id"), table_name="projects")
    op.create_index(op.f("projects_slug_idx"), "projects", ["slug"], unique=True)
    op.create_index(op.f("projects_user_id_idx"), "projects", ["user_id"], unique=False)
    op.drop_index(op.f("ix_prompt_registry_project_id"), table_name="prompt_registry")
    op.drop_index(op.f("ix_prompt_registry_prompt_hash"), table_name="prompt_registry")
    op.drop_index(op.f("ix_prompt_registry_run_id"), table_name="prompt_registry")
    op.create_index(
        op.f("prompt_registry_project_id_idx"), "prompt_registry", ["project_id"], unique=False
    )
    op.create_index(
        op.f("prompt_registry_prompt_hash_idx"), "prompt_registry", ["prompt_hash"], unique=False
    )
    op.create_index(op.f("prompt_registry_run_id_idx"), "prompt_registry", ["run_id"], unique=False)
    op.drop_index(op.f("ix_room_messages_room_id"), table_name="room_messages")
    op.create_index(op.f("room_messages_room_id_idx"), "room_messages", ["room_id"], unique=False)
    op.drop_index(op.f("ix_rooms_project_id"), table_name="rooms")
    op.create_index(op.f("rooms_project_id_idx"), "rooms", ["project_id"], unique=False)
    op.drop_index(op.f("ix_run_metrics_project_id"), table_name="run_metrics")
    op.drop_index(op.f("ix_run_metrics_run_id"), table_name="run_metrics")
    op.drop_constraint(op.f("run_metrics_run_id_key"), "run_metrics", type_="unique")
    op.create_index(op.f("run_metrics_project_id_idx"), "run_metrics", ["project_id"], unique=False)
    op.create_index(op.f("run_metrics_run_id_idx"), "run_metrics", ["run_id"], unique=True)
    op.drop_index(op.f("ix_run_steps_agent_config_id"), table_name="run_steps")
    op.drop_index(op.f("ix_run_steps_run_id"), table_name="run_steps")
    op.create_index(
        op.f("run_steps_agent_config_id_idx"), "run_steps", ["agent_config_id"], unique=False
    )
    op.create_index(op.f("run_steps_run_id_idx"), "run_steps", ["run_id"], unique=False)
    op.drop_index(op.f("ix_runs_project_id"), table_name="runs")
    op.drop_index(op.f("ix_runs_workflow_id"), table_name="runs")
    op.create_index(op.f("runs_project_id_idx"), "runs", ["project_id"], unique=False)
    op.create_index(op.f("runs_workflow_id_idx"), "runs", ["workflow_id"], unique=False)
    op.drop_index(op.f("ix_schedules_project_id"), table_name="schedules")
    op.drop_index(op.f("ix_schedules_workflow_id"), table_name="schedules")
    op.create_index(op.f("schedules_project_id_idx"), "schedules", ["project_id"], unique=False)
    op.create_index(op.f("schedules_workflow_id_idx"), "schedules", ["workflow_id"], unique=False)
    op.drop_index(op.f("ix_tool_calls_message_id"), table_name="tool_calls")
    op.create_index(op.f("tool_calls_message_id_idx"), "tool_calls", ["message_id"], unique=False)
    op.drop_index(op.f("ix_trace_events_created_at"), table_name="trace_events")
    op.drop_index(op.f("ix_trace_events_event_type"), table_name="trace_events")
    op.drop_index(op.f("ix_trace_events_project_id"), table_name="trace_events")
    op.drop_index(op.f("ix_trace_events_run_id"), table_name="trace_events")
    op.drop_index(op.f("ix_trace_events_trace_id"), table_name="trace_events")
    op.create_index(
        op.f("trace_events_created_at_idx"), "trace_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("trace_events_event_type_idx"), "trace_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("trace_events_project_id_idx"), "trace_events", ["project_id"], unique=False
    )
    op.create_index(op.f("trace_events_run_id_idx"), "trace_events", ["run_id"], unique=False)
    op.create_index(op.f("trace_events_trace_id_idx"), "trace_events", ["trace_id"], unique=False)
    op.drop_index(op.f("ix_user_slash_commands_user_id"), table_name="user_slash_commands")
    op.create_index(
        op.f("user_slash_commands_user_id_idx"), "user_slash_commands", ["user_id"], unique=False
    )
    op.drop_index(op.f("ix_workflows_project_id"), table_name="workflows")
    op.create_index(op.f("workflows_project_id_idx"), "workflows", ["project_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("workflows_project_id_idx"), table_name="workflows")
    op.create_index(op.f("ix_workflows_project_id"), "workflows", ["project_id"], unique=False)
    op.drop_index(op.f("user_slash_commands_user_id_idx"), table_name="user_slash_commands")
    op.create_index(
        op.f("ix_user_slash_commands_user_id"), "user_slash_commands", ["user_id"], unique=False
    )
    op.drop_index(op.f("trace_events_trace_id_idx"), table_name="trace_events")
    op.drop_index(op.f("trace_events_run_id_idx"), table_name="trace_events")
    op.drop_index(op.f("trace_events_project_id_idx"), table_name="trace_events")
    op.drop_index(op.f("trace_events_event_type_idx"), table_name="trace_events")
    op.drop_index(op.f("trace_events_created_at_idx"), table_name="trace_events")
    op.create_index(op.f("ix_trace_events_trace_id"), "trace_events", ["trace_id"], unique=False)
    op.create_index(op.f("ix_trace_events_run_id"), "trace_events", ["run_id"], unique=False)
    op.create_index(
        op.f("ix_trace_events_project_id"), "trace_events", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_trace_events_event_type"), "trace_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_trace_events_created_at"), "trace_events", ["created_at"], unique=False
    )
    op.drop_index(op.f("tool_calls_message_id_idx"), table_name="tool_calls")
    op.create_index(op.f("ix_tool_calls_message_id"), "tool_calls", ["message_id"], unique=False)
    op.drop_index(op.f("schedules_workflow_id_idx"), table_name="schedules")
    op.drop_index(op.f("schedules_project_id_idx"), table_name="schedules")
    op.create_index(op.f("ix_schedules_workflow_id"), "schedules", ["workflow_id"], unique=False)
    op.create_index(op.f("ix_schedules_project_id"), "schedules", ["project_id"], unique=False)
    op.drop_index(op.f("runs_workflow_id_idx"), table_name="runs")
    op.drop_index(op.f("runs_project_id_idx"), table_name="runs")
    op.create_index(op.f("ix_runs_workflow_id"), "runs", ["workflow_id"], unique=False)
    op.create_index(op.f("ix_runs_project_id"), "runs", ["project_id"], unique=False)
    op.drop_index(op.f("run_steps_run_id_idx"), table_name="run_steps")
    op.drop_index(op.f("run_steps_agent_config_id_idx"), table_name="run_steps")
    op.create_index(op.f("ix_run_steps_run_id"), "run_steps", ["run_id"], unique=False)
    op.create_index(
        op.f("ix_run_steps_agent_config_id"), "run_steps", ["agent_config_id"], unique=False
    )
    op.drop_index(op.f("run_metrics_run_id_idx"), table_name="run_metrics")
    op.drop_index(op.f("run_metrics_project_id_idx"), table_name="run_metrics")
    op.create_unique_constraint(
        op.f("run_metrics_run_id_key"),
        "run_metrics",
        ["run_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(op.f("ix_run_metrics_run_id"), "run_metrics", ["run_id"], unique=False)
    op.create_index(op.f("ix_run_metrics_project_id"), "run_metrics", ["project_id"], unique=False)
    op.drop_index(op.f("rooms_project_id_idx"), table_name="rooms")
    op.create_index(op.f("ix_rooms_project_id"), "rooms", ["project_id"], unique=False)
    op.drop_index(op.f("room_messages_room_id_idx"), table_name="room_messages")
    op.create_index(op.f("ix_room_messages_room_id"), "room_messages", ["room_id"], unique=False)
    op.drop_index(op.f("prompt_registry_run_id_idx"), table_name="prompt_registry")
    op.drop_index(op.f("prompt_registry_prompt_hash_idx"), table_name="prompt_registry")
    op.drop_index(op.f("prompt_registry_project_id_idx"), table_name="prompt_registry")
    op.create_index(op.f("ix_prompt_registry_run_id"), "prompt_registry", ["run_id"], unique=False)
    op.create_index(
        op.f("ix_prompt_registry_prompt_hash"), "prompt_registry", ["prompt_hash"], unique=False
    )
    op.create_index(
        op.f("ix_prompt_registry_project_id"), "prompt_registry", ["project_id"], unique=False
    )
    op.drop_index(op.f("projects_user_id_idx"), table_name="projects")
    op.drop_index(op.f("projects_slug_idx"), table_name="projects")
    op.create_index(op.f("ix_projects_user_id"), "projects", ["user_id"], unique=False)
    op.create_index(op.f("ix_projects_slug"), "projects", ["slug"], unique=True)
    op.drop_index(op.f("messages_conversation_id_idx"), table_name="messages")
    op.create_index(
        op.f("ix_messages_conversation_id"), "messages", ["conversation_id"], unique=False
    )
    op.drop_index(op.f("message_ratings_user_id_idx"), table_name="message_ratings")
    op.drop_index(op.f("message_ratings_message_id_idx"), table_name="message_ratings")
    op.create_index(
        op.f("ix_message_ratings_user_id"), "message_ratings", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_message_ratings_message_id"), "message_ratings", ["message_id"], unique=False
    )
    op.drop_index(op.f("knowledge_documents_project_id_idx"), table_name="knowledge_documents")
    op.drop_index(op.f("knowledge_documents_agent_config_id_idx"), table_name="knowledge_documents")
    op.create_index(
        op.f("ix_knowledge_documents_project_id"),
        "knowledge_documents",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_documents_agent_config_id"),
        "knowledge_documents",
        ["agent_config_id"],
        unique=False,
    )
    op.drop_index(op.f("conversations_user_id_idx"), table_name="conversations")
    op.create_index(op.f("ix_conversations_user_id"), "conversations", ["user_id"], unique=False)
    op.drop_index(op.f("conversation_shares_shared_with_idx"), table_name="conversation_shares")
    op.drop_index(op.f("conversation_shares_conversation_id_idx"), table_name="conversation_shares")
    op.create_index(
        op.f("ix_conversation_shares_shared_with"),
        "conversation_shares",
        ["shared_with"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_shares_conversation_id"),
        "conversation_shares",
        ["conversation_id"],
        unique=False,
    )
    op.drop_index(op.f("chat_files_user_id_idx"), table_name="chat_files")
    op.create_index(op.f("ix_chat_files_user_id"), "chat_files", ["user_id"], unique=False)
    op.drop_index(op.f("agent_configs_project_id_idx"), table_name="agent_configs")
    op.create_index(
        op.f("ix_agent_configs_project_id"), "agent_configs", ["project_id"], unique=False
    )
    op.drop_index(op.f("handoffs_to_step_id_idx"), table_name="handoffs")
    op.drop_index(op.f("handoffs_to_agent_id_idx"), table_name="handoffs")
    op.drop_index(op.f("handoffs_run_id_idx"), table_name="handoffs")
    op.drop_index(op.f("handoffs_project_id_idx"), table_name="handoffs")
    op.drop_index(op.f("handoffs_from_step_id_idx"), table_name="handoffs")
    op.drop_index(op.f("handoffs_from_agent_id_idx"), table_name="handoffs")
    op.drop_table("handoffs")
    op.drop_index(op.f("secrets_user_id_idx"), table_name="secrets")
    op.drop_table("secrets")
    op.drop_index(op.f("integrations_user_id_idx"), table_name="integrations")
    op.drop_table("integrations")
    # ### end Alembic commands ###
